# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Rft_dict_get_nwords <- function(r_dict) {
    .Call('fastTextR_Rft_dict_get_nwords', PACKAGE = 'fastTextR', r_dict)
}

Rft_dict_get_nlabels <- function(r_dict) {
    .Call('fastTextR_Rft_dict_get_nlabels', PACKAGE = 'fastTextR', r_dict)
}

Rft_dict_get_ntokens <- function(r_dict) {
    .Call('fastTextR_Rft_dict_get_ntokens', PACKAGE = 'fastTextR', r_dict)
}

Rft_dict_get_word <- function(r_dict, i) {
    .Call('fastTextR_Rft_dict_get_word', PACKAGE = 'fastTextR', r_dict, i)
}

Rft_dict_get_words <- function(r_dict, ind) {
    .Call('fastTextR_Rft_dict_get_words', PACKAGE = 'fastTextR', r_dict, ind)
}

Rft_dict_get_all_words <- function(r_dict) {
    .Call('fastTextR_Rft_dict_get_all_words', PACKAGE = 'fastTextR', r_dict)
}

Rft_dict_get_label <- function(r_dict, i) {
    .Call('fastTextR_Rft_dict_get_label', PACKAGE = 'fastTextR', r_dict, i)
}

Rft_dict_get_labels <- function(r_dict, ind) {
    .Call('fastTextR_Rft_dict_get_labels', PACKAGE = 'fastTextR', r_dict, ind)
}

Rft_dict_get_all_labels <- function(r_dict) {
    .Call('fastTextR_Rft_dict_get_all_labels', PACKAGE = 'fastTextR', r_dict)
}

Rft_dict_read_from_file <- function(r_dict, file_name) {
    .Call('fastTextR_Rft_dict_read_from_file', PACKAGE = 'fastTextR', r_dict, file_name)
}

Rft_ft_dim_input_matrix <- function(r_ft) {
    .Call('fastTextR_Rft_ft_dim_input_matrix', PACKAGE = 'fastTextR', r_ft)
}

Rft_ft_dim_output_matrix <- function(r_ft) {
    .Call('fastTextR_Rft_ft_dim_output_matrix', PACKAGE = 'fastTextR', r_ft)
}

Rft_ft_get_args <- function(r_ft) {
    .Call('fastTextR_Rft_ft_get_args', PACKAGE = 'fastTextR', r_ft)
}

Rft_ft_get_dict <- function(r_ft) {
    .Call('fastTextR_Rft_ft_get_dict', PACKAGE = 'fastTextR', r_ft)
}

Rft_ft_get_input_matrix <- function(r_ft) {
    .Call('fastTextR_Rft_ft_get_input_matrix', PACKAGE = 'fastTextR', r_ft)
}

Rft_ft_get_output_matrix <- function(r_ft) {
    .Call('fastTextR_Rft_ft_get_output_matrix', PACKAGE = 'fastTextR', r_ft)
}

Rft_ft_get_model <- function(r_ft) {
    .Call('fastTextR_Rft_ft_get_model', PACKAGE = 'fastTextR', r_ft)
}

Rft_ft_get_token_count <- function(r_ft) {
    .Call('fastTextR_Rft_ft_get_token_count', PACKAGE = 'fastTextR', r_ft)
}

Rft_ft_get_model_type <- function(r_ft) {
    .Call('fastTextR_Rft_ft_get_model_type', PACKAGE = 'fastTextR', r_ft)
}

Rft_new_model <- function() {
    .Call('fastTextR_Rft_new_model', PACKAGE = 'fastTextR')
}

Rft_new_args <- function() {
    .Call('fastTextR_Rft_new_args', PACKAGE = 'fastTextR')
}

Rft_new_dict <- function(control) {
    .Call('fastTextR_Rft_new_dict', PACKAGE = 'fastTextR', control)
}

Rft_load_model <- function(file_name) {
    .Call('fastTextR_Rft_load_model', PACKAGE = 'fastTextR', file_name)
}

Rft_save_model <- function(ft, file_name) {
    .Call('fastTextR_Rft_save_model', PACKAGE = 'fastTextR', ft, file_name)
}

Rft_args_to_list <- function(args) {
    .Call('fastTextR_Rft_args_to_list', PACKAGE = 'fastTextR', args)
}

Rft_train <- function(control, save_to_file) {
    .Call('fastTextR_Rft_train', PACKAGE = 'fastTextR', control, save_to_file)
}

Rft_test <- function(ft, test_file, k_most_likely) {
    .Call('fastTextR_Rft_test', PACKAGE = 'fastTextR', ft, test_file, k_most_likely)
}

Rft_predict_to_file <- function(ft, newdata_file, result_file, k_most_likely, print_prob) {
    .Call('fastTextR_Rft_predict_to_file', PACKAGE = 'fastTextR', ft, newdata_file, result_file, k_most_likely, print_prob)
}

Rft_predict <- function(ft, newdata_file, k_most_likely, print_prob) {
    .Call('fastTextR_Rft_predict', PACKAGE = 'fastTextR', ft, newdata_file, k_most_likely, print_prob)
}

Rft_vec_predict <- function(ft, newdata, k_most_likely, print_prob) {
    .Call('fastTextR_Rft_vec_predict', PACKAGE = 'fastTextR', ft, newdata, k_most_likely, print_prob)
}

Rft_get_word_vectors <- function(ft, words) {
    .Call('fastTextR_Rft_get_word_vectors', PACKAGE = 'fastTextR', ft, words)
}

Rft_get_all_word_vectors <- function(ft) {
    .Call('fastTextR_Rft_get_all_word_vectors', PACKAGE = 'fastTextR', ft)
}

Rft_similarity <- function(ft, word_a, word_b) {
    .Call('fastTextR_Rft_similarity', PACKAGE = 'fastTextR', ft, word_a, word_b)
}

Rft_k_most_silmilar <- function(ft, words, k) {
    .Call('fastTextR_Rft_k_most_silmilar', PACKAGE = 'fastTextR', ft, words, k)
}

clean_text <- function(x) {
    .Call('fastTextR_clean_text', PACKAGE = 'fastTextR', x)
}

